// <auto-generated />
using System;
using Anabasis.Demo.Actor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anabasis.Demo.Actor.Migrations
{
    [DbContext(typeof(TradeAggregateSnapshotDbContext))]
    [Migration("20220309125423_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Anabasis.Common.AggregateSnapshot", b =>
                {
                    b.Property<string>("StreamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventFilter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerializedAggregate")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StreamId", "EventFilter", "Version");

                    b.ToTable("AggregateSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
